[time]
start = "20191001 00"
end = "20191001 23"

[datasets]
METAR = false
SAO = false
MARITIME = false
MODERNIZED_COOP = false
URBANET = false
INTEGRATED_MESONET = true
HYDROLOGICAL_SURFACE = false
MULTI_AGENCY_PROFILER = false
SNOW = false
WISDOM = false
SATELLITE_WIND_3_HOUR = false
SATELLITE_WIND_1_HOUR = false
SATELLITE_SOUNDING = false
SATELLITE_RADIANCE = false
RADIOMETER = false
RADIOSONDE = false
AUTOMATED_AIRCRAFT_REPORTS = false
AUTOMATED_AIRCRAFT_PROFILES_AT_AIRPORTS = false
NOAA_PROFILER_NETWORK = false
CRN = false
HCN = false
NEPP = false
HFMETAR = false
RWIS = false

[ftp]
server_location = "DEFAULT"
